### ISSUE TITLE
sh tlmgr command not found

### ISSUE THREAD

**Issue by skhadrao** [yihui/tinytex#198] opened 2020-04-17 01:47 UTC
Hello, I'm using tidytex to create pdf files via markdown in Rstudion, here is my code 
```
rmarkdown::render(
    input = "/home/skhadraoui/workspace/1-Programmes/Etape-7_Restitution_college_pdf.Rmd",
    output_format = "pdf_document",
    output_file = paste(
      "/home/skhadraoui/workspace/4-Restitutions/Restitution_College/",
      paste(code_operation, college, "Restitution",
            sep =
              "_"),
      ".pdf",
      sep = ""
    ),
    output_options = list(),
    encoding = "UTF-8",
    clean = FALSE,
    quiet = TRUE
  )

```

I can install tinytex succefully like 
install.packages('tinytex')
tinytex::install_tinytex()

But, when I'm running my code, the error in the below image ?

Any help ?
![image](https://user-images.githubusercontent.com/43041852/79523281-0d801380-805e-11ea-92cb-5b0dfb2f4068.png)

**Comment by yihui** [comment] 2020-04-17 02:36
Duplicate of #197

**Comment by skhadrao** [comment] 2020-04-17 10:28
Hello Yihui, 

The installation seems to work right now, but I still have an issue WHILE TRYING TO PRODUCE 'png' images ?

![image](https://user-images.githubusercontent.com/43041852/79559918-d5e98980-80a6-11ea-81f0-752fe988fd2e.png)

**Comment by yihui** [comment] 2020-04-18 03:41
I'm going to close this issue since the original issue has been resolved. For the new issue, please follow the [issue guide](new) (which you deleted when filing this issue; in particular, please don't forget provide reproducible examples). Thanks!

**Closed by yihui** 2020-04-18 03:41 UTC

**Comment by skhadrao** [comment] 2020-04-18 16:21
Thanks Yihui ! 

I've opened another issue !
