### ISSUE TITLE
no translations available

### ISSUE THREAD

**Issue by cderv** [yihui/tinytex#305] opened 2021-04-27 08:52 UTC
Weird message now when installing a new TinyTex version - I got a message about no translations available each time a command is run. 

````
> tinytex::install_tinytex()
trying URL 'https://yihui.org/tinytex/TinyTeX-1.zip'
Content type 'application/octet-stream' length 103365837 bytes (98.6 MB)
downloaded 98.6 MB


  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)


  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)

tlmgr option repository "ctan"

  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)

tlmgr.pl: setting default package repository to https://mirror.ctan.org/systems/texlive/tlnet
tlmgr.pl: updating C:/Users/chris/AppData/Roaming/TinyTeX/tlpkg/texlive.tlpdb
````

I got it with other command too 

```
> tinytex::tlmgr("--version")
tlmgr --version

  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)

tlmgr revision 58938 (2021-04-21 23:26:24 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2021
```

I did not get that before with previous TeX Live 2020. 

@yihui Do you know about this message ? 

Is there something missing in our build ?

**Comment by yihui** [comment] 2021-04-27 14:03
I've never seen this before, and I can't tell if this is new or has existed before, because I'm always using the en_US locale. To verify, you can download the prebuilt packages from a few days ago: https://ci.appveyor.com/project/yihui/tinytex/history e.g., https://ci.appveyor.com/project/yihui/tinytex/builds/38845501/job/9b7u3odxniqi2b95/artifacts install the zip archive with `tinytex:::install_prebuilt('TinyTeX-1.zip')`, and see if it emits the same message.

Perhaps the quickest way is ask @norbusan if there is a recent change in `install-tl` or `tlmgr`.

**Comment by cderv** [comment] 2021-04-27 14:22
Thanks, I'll try to see with which version it happens. This is not new but I reported it today 😅 
I think first time was when we upgraded TinyTeX to use TeX Live 2021.

**Comment by norbusan** [comment] 2021-04-28 00:15
Hmm, not sure whether something has changed. But the message clearly states the reason: Is `texlive-msg-translations` installed?

Just to make sure, it is **not** installed when installing `scheme-infraonly` so you might want to add it manually.

**Comment by yihui** [comment] 2021-04-28 02:40
Indeed `texlive-msg-translations` is not installed. I'll consider including it.

Since I have never seen this message before, and no one has ever reported it, either, I thought it was something introduced recently (like in the past few days) into TeX Live.

However, when I read the documentation at http://tug.org/texlive/doc.html#install-tl-xlate, I thought the translations would only be relevant to the GUI mode: 

> The messages in the TeX Live installer and TeX Live Manager are available in various languages (**when running in GUI mode only**; we want to keep text mode as simple as possible).

In TinyTeX, I don't use the GUI mode (neither `install-tl` nor `tlmgr`), so it seems the message should have been suppressed.

**Comment by norbusan** [comment] 2021-04-28 03:38
Ah indeed, with TL2021 we have started to support translations of the TUI (tlmgr) itself, too. Hardly any string is encoded by now, but this might change in the future.

**Comment by yihui** [comment] 2021-04-28 16:35
Okay, I see. Is it possible not to emit the message when translations are not available? To me, the translation is a "nice-to-have" but not necessity. The message is a little overwhelming and seems to indicate that something critical is missing (and it's printed every time `tlmgr` is called). From my experience with R, its Chinese translation was far worse than no translation, which was why I redid the translation about 14 years ago but I didn't finish it. Even today, some messages in Chinese are still obscure to me compared to the original English text. I didn't read the Chinese translation in TeX Live, so I don't know its quality. That said, technical terms are often hard to translate.

So it'll be great if this could be an opt-in feature, i.e., actively opt-in by installing `texlive-msg-translations`. If not possible, it'd be still good to have a way to disable the message (i.e. "I know I can use translations but I don't really need it; thank you"), e.g., `tlmgr option lang en_US`.

**Comment by yihui** [comment] 2021-05-18 18:28
> e.g., `tlmgr option lang en_US`

I guess I've found the right command: `tlmgr conf tlmgr gui-lang en`. @cderv Could you try this and see if it would suppress the message for subsequent `tlmgr` calls?

**Comment by yihui** [comment] 2021-05-18 18:53
@norbusan I feel it's either I understand too little about Perl (which is true) or there is a bug in `tlmgr.pl` (lines 429-431):

```perl
  # prepare for loading of lang.pl which expects $::lang and $::opt_lang
  $::opt_lang = $config{"gui-lang"} if (defined($config{"gui-lang"}));
  $::opt_lang = $opts{"gui-lang"} if (defined($opts{"gui-lang"}));
```

My system language is `en_US`. After I set `tlmgr conf tlmgr gui-lang zh`, `$::opt_lang` is still undefined. I was expecting it to become `zh`, hence I would see the message about missing translations.

**Comment by cderv** [comment] 2021-05-18 19:50
> tlmgr conf tlmgr gui-lang en

This was correctly set it seems
````r
> tinytex::tlmgr_conf(c("tlmgr", "gui-lang", "en"))
tlmgr conf tlmgr gui-lang en

  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)

tlmgr.pl: setting tlmgr gui-lang to en (in C:/Users/chris/AppData/Roaming/TinyTeX/texmf-config/tlmgr/config)

> xfun::file_string("C:/Users/chris/AppData/Roaming/TinyTeX/texmf-config/tlmgr/config")
gui-lang = en
````
But still got the message after this 
````r
> tinytex::tlmgr("--version")
tlmgr --version

  Sorry, no translations available for fr_FR (nor fr); falling back to English.
    Make sure that you have the package "texlive-msg-translations" installed.
    (If you'd like to help translate the installer's messages, please see
    http://tug.org/texlive/doc.html#install-tl-xlate for information.)

tlmgr revision 59154 (2021-05-10 00:00:07 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2021
````

Is there any restarting ? reload ? reset that needs to be done for a config to be taken into account ? 
But I guess this could be due to the potential issue you mentioned above.

**Comment by norbusan** [comment] 2021-05-19 22:55
> My system language is `en_US`. After I set `tlmgr conf tlmgr gui-lang zh`, `$::opt_lang` is still undefined. 

Well, the change of loading was introduced not by me, and obviously it was done incorrectly.

The problem is that at the time the translations are loaded, the configuration file hasn't been loaded, so the variable is unset ;-)

I will check whether shuffling the invocations is fine.

Thanks for the report!

**Comment by yihui** [comment] 2021-05-26 05:21
@norbusan Any news? (no hurry, though)

**Comment by norbusan** [comment] 2021-05-26 08:24
Should already be fixed in tlcritical ... but it isn't pushed out to tlnet for now.

If you can test from tlcritical that would help.

Best

**Comment by yihui** [comment] 2021-05-26 13:58
@norbusan I tried `tlmgr --repository=ftp://tug.org/texlive/tlcritical update --self` and the message was indeed gone when my `gui-lang` setting is different with my system language. Do you have an idea about when the change will be pushed out to tlnet? Thanks!

In the meantime, I saw Karl also made this change: https://www.tug.org/svn/texlive/trunk/Master/tlpkg/TeXLive/trans.pl?r1=59224&r2=59285 I think that will hide the message from normal users as well (since the message is displayed only in the debug mode). Thanks @kberry!

**Comment by norbusan** [comment] 2021-05-26 14:19
Yes, one was about silencing the warning, the other about fixing the usage of gui-lang in the config file.

I am not sure when we push out the changes, though.

**Comment by kberry** [comment] 2021-05-27 15:06
i enabled tlcritical->tlnet for tonight's update.

**Comment by cderv** [comment] 2021-05-28 10:49
I think the update has passed. I confirm that I don't have the message anymore after updating today. 
Yihui, I did a `tinytex::reinstall_tinytex()`

**Comment by yihui** [comment] 2021-05-28 13:29
I can also confirm it. In addition, the `-v` flag can trigger the debug message, too:

```sh
$ LANG=de_DE.UTF-8 tlmgr update --self
tlmgr: no self-updates for tlmgr available

$ LANG=fr_FR.UTF-8 tlmgr update --self -v
D:no translations available for fr_FR (nor fr); falling back to English
tlmgr: no self-updates for tlmgr available
```

Thanks again @norbusan and @kberry!

**Closed** 2021-05-28 13:30 UTC
